# 개발 환경 설정
spring:
  datasource:
    url: jdbc:postgresql://db:5432/maruni-db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 개발환경 Swagger 설정
swagger:
  server:
    url: http://localhost:8080
    description: 개발 서버

# 개발환경 로깅
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.example.login: debug